import {
  DiscoverySessionResponse,
  DisplayStory,
  SegmentPage,
  SessionSegmentResponse,
  SessionTranscriptSegmentMessage,
  SuggestionResponse,
  SuggestionType,
} from './discovery.models';

/**
 * Pure feed-assembly logic for the discovery chat: how a session's raw parts
 * (historical transcript text, live segments, decisions, generated stories)
 * merge into one ordered list of render-ready items. Kept free of Angular so
 * the ordering rules are unit-testable.
 */

/** An immutable record of a decision taken on a suggestion, rendered inline in the feed. */
export interface DecisionEntry {
  /** The decided suggestion's id (stable across REST and realtime events). */
  id: string;
  outcome: 'ACCEPTED' | 'DISMISSED';
  type: SuggestionType;
  /** Display label: the (draft) story title, or the clarifying question text. */
  label: string | null;
  /** Story the decision created/updated, when the backend reported one. */
  storyId: string | null;
  occurredAt: string;
  /**
   * The highest live-segment sequence present when the decision happened; the
   * entry is rendered right after that segment (-1 = before any segment).
   */
  anchorSequence: number;
}

export type FeedItem =
  | { kind: 'paragraph'; id: string; text: string }
  | { kind: 'segment'; id: string; segment: SessionTranscriptSegmentMessage }
  | { kind: 'decision'; id: string; decision: DecisionEntry }
  | { kind: 'story'; id: string; story: DisplayStory };

/** One session's chunk of the feed (sessions are the chat's natural separators). */
export interface SessionBlock {
  session: DiscoverySessionResponse;
  /**
   * Raw transcript text — used only as a fallback when the structured segments
   * endpoint is unavailable (older backend). Null once segments load, until
   * fetched, or when empty.
   */
  transcript: string | null;
  /**
   * Transcript segments, ascending by sequence: live ones merged from realtime,
   * or a historical session's persisted segments loaded on open (each carrying
   * its `occurredAt`).
   */
  segments: SessionTranscriptSegmentMessage[];
  /** Decisions taken on this session's suggestions, oldest first. */
  decisions: DecisionEntry[];
  /** Stories generated by this session. */
  stories: DisplayStory[];
  /**
   * True for a loaded historical (non-live) session, whose parts carry absolute
   * timestamps and are merged in chronological order. False for live sessions,
   * which keep the anchor-sequence interleave.
   */
  chronological: boolean;
  /**
   * Whether older segments remain before the lowest loaded one (historical
   * blocks only) — drives intra-session scroll-up pagination.
   */
  hasMoreSegments: boolean;
  /** True while an older-segment chunk of this block is being fetched. */
  loadingSegments: boolean;
  /** False while the block's transcript/stories are still being fetched. */
  loaded: boolean;
}

/** The lowest loaded segment sequence, or null when none are loaded (the cursor for the next older page). */
export function lowestSequence(
  segments: readonly SessionTranscriptSegmentMessage[],
): number | null {
  if (segments.length === 0) return null;
  return segments.reduce((min, s) => Math.min(min, s.sequence), Number.POSITIVE_INFINITY);
}

/** Adapts a persisted historical segment to the live-segment shape the feed renders (always final). */
export function historicalSegmentToMessage(
  sessionId: string,
  segment: SessionSegmentResponse,
): SessionTranscriptSegmentMessage {
  return {
    sessionId,
    type: 'TRANSCRIPT_SEGMENT',
    occurredAt: segment.occurredAt,
    sequence: segment.sequence,
    speakerLabel: segment.speakerLabel,
    text: segment.text,
    startMs: segment.startMs,
    endMs: segment.endMs,
    isFinal: true,
  };
}

/**
 * Normalizes the still-settling segments-page payload into a {@link SegmentPage}.
 * Accepts a bare array, an object with a `hasMore` flag, or a Spring-style
 * PageResponse (`content` + `page.hasNext`). Unknown shapes degrade to empty.
 */
export function normalizeSegmentPage(raw: unknown): SegmentPage {
  if (Array.isArray(raw)) {
    return { segments: raw as SessionSegmentResponse[], hasMore: false };
  }
  if (raw && typeof raw === 'object') {
    const obj = raw as Record<string, unknown>;
    const list = Array.isArray(obj['segments'])
      ? (obj['segments'] as SessionSegmentResponse[])
      : Array.isArray(obj['content'])
        ? (obj['content'] as SessionSegmentResponse[])
        : [];
    const page = obj['page'] as { hasNext?: boolean; hasPrevious?: boolean } | undefined;
    const hasMore =
      typeof obj['hasMore'] === 'boolean'
        ? (obj['hasMore'] as boolean)
        : // Older-first cursor: "more older segments remain" maps to the page's
          // hasPrevious when present, else hasNext, else false.
          (page?.hasPrevious ?? page?.hasNext ?? false);
    return { segments: list, hasMore };
  }
  return { segments: [], hasMore: false };
}

/** Splits a historical transcript blob into paragraph items (speaker-agnostic bubbles). */
export function transcriptToItems(sessionId: string, transcript: string | null): FeedItem[] {
  if (!transcript) return [];
  return transcript
    .split(/\n+/)
    .map((line) => line.trim())
    .filter((line) => line.length > 0)
    .map((text, index) => ({ kind: 'paragraph' as const, id: `${sessionId}:p${index}`, text }));
}

/**
 * Upserts a live segment by sequence (a hypothesis is replaced by its final),
 * keeping ascending order. Live WebSocket segments may arrive without an
 * `occurredAt` (only the historical `/segments` payload guarantees one), which
 * leaves the bubble's time blank; when it is missing we stamp the client arrival
 * time so every bubble always shows a timestamp. Historical segments always
 * carry a real `occurredAt` and are never overwritten.
 */
export function upsertSegment(
  segments: readonly SessionTranscriptSegmentMessage[],
  segment: SessionTranscriptSegmentMessage,
  arrivalTime: string = new Date().toISOString(),
): SessionTranscriptSegmentMessage[] {
  const stamped = segment.occurredAt ? segment : { ...segment, occurredAt: arrivalTime };
  return [...segments.filter((s) => s.sequence !== stamped.sequence), stamped].sort(
    (a, b) => a.sequence - b.sequence,
  );
}

/**
 * Merges a live/paused session's recorded `historical` segments UNDER the live
 * WebSocket segments already present: a live segment at a sequence wins (a real
 * final segment supersedes the persisted one), so only historical segments whose
 * sequence has no live counterpart are added. The result is deduped by sequence
 * and kept ascending. Used when a live block loads its persisted transcript while
 * live segments may already have merged in.
 */
export function mergeHistoricalUnderLive(
  live: readonly SessionTranscriptSegmentMessage[],
  historical: readonly SessionTranscriptSegmentMessage[],
): SessionTranscriptSegmentMessage[] {
  const seen = new Set(live.map((s) => s.sequence));
  const merged = [...live];
  for (const segment of historical) {
    if (seen.has(segment.sequence)) continue;
    seen.add(segment.sequence);
    merged.push(segment);
  }
  return merged.sort((a, b) => a.sequence - b.sequence);
}

/** The highest final segment sequence, or -1 when there are none (decision anchor). */
export function lastSequence(segments: readonly SessionTranscriptSegmentMessage[]): number {
  return segments.reduce((max, s) => Math.max(max, s.sequence), -1);
}

/**
 * The anchor sequence a decision should take in a LIVE block, so it lands at the
 * transcript moment of the SUGGESTION it resolves rather than at accept time.
 *
 * We place it right after the last segment whose `occurredAt` is at or before
 * the suggestion's own `createdAt` (the moment the AI proposed it). This keeps
 * an accepted story sitting chronologically among the segments instead of being
 * pushed to the bottom by the accept-time latest sequence.
 *
 * Falls back to {@link lastSequence} only when the suggestion carries no usable
 * time — the best signal available, matching the old behavior. When the time IS
 * valid but earlier than every segment, the decision anchors before them all
 * (-1). NOTE: this relies on `suggestion.createdAt`; if the backend later
 * exposes the originating segment sequence directly, prefer that.
 */
export function anchorSequenceForSuggestion(
  segments: readonly SessionTranscriptSegmentMessage[],
  suggestionCreatedAt: string | null | undefined,
): number {
  const at = suggestionCreatedAt ? Date.parse(suggestionCreatedAt) : Number.NaN;
  if (Number.isNaN(at)) return lastSequence(segments);
  let anchor = -1;
  for (const segment of segments) {
    const segTime = Date.parse(segment.occurredAt);
    if (!Number.isNaN(segTime) && segTime <= at) {
      anchor = Math.max(anchor, segment.sequence);
    }
  }
  return anchor;
}

/** Builds a decision entry from a resolved suggestion, anchored after the current last segment. */
export function toDecisionEntry(
  suggestion: SuggestionResponse,
  outcome: 'ACCEPTED' | 'DISMISSED',
  anchorSequence: number,
  occurredAt: string = new Date().toISOString(),
): DecisionEntry {
  return {
    id: suggestion.id,
    outcome,
    type: suggestion.type,
    label: suggestion.type === 'CLARIFYING_QUESTION' ? suggestion.question : suggestion.draftTitle,
    storyId: suggestion.resolvedStoryId ?? suggestion.targetStoryId,
    occurredAt,
    anchorSequence,
  };
}

interface BuildInput {
  session: { id: string };
  transcript: string | null;
  segments: readonly SessionTranscriptSegmentMessage[];
  decisions: readonly DecisionEntry[];
  stories: readonly DisplayStory[];
  /** When true, merge segments/decisions/stories by absolute timestamp (historical block). */
  chronological?: boolean;
}

/**
 * Merges one session's parts into its ordered feed items. Two orderings:
 *
 * - Live blocks (default): historical transcript paragraphs, then live segments
 *   with each decision inserted right after its anchor segment, then generated
 *   stories not already shown as an accepted decision.
 * - Historical blocks (`chronological`): every part carries an absolute
 *   timestamp, so segments, decisions and stories interleave in time order.
 */
export function buildSessionItems(block: BuildInput): FeedItem[] {
  const decidedStoryIds = new Set(
    block.decisions.filter((d) => d.outcome === 'ACCEPTED' && d.storyId).map((d) => d.storyId),
  );

  if (block.chronological) {
    return buildChronologicalItems(block, decidedStoryIds);
  }

  const items: FeedItem[] = transcriptToItems(block.session.id, block.transcript);

  // Decisions grouped by anchor so several decisions after one segment keep their order.
  const byAnchor = new Map<number, DecisionEntry[]>();
  for (const decision of block.decisions) {
    const list = byAnchor.get(decision.anchorSequence) ?? [];
    list.push(decision);
    byAnchor.set(decision.anchorSequence, list);
  }
  const pushDecisions = (anchor: number): void => {
    for (const decision of byAnchor.get(anchor) ?? []) {
      items.push({ kind: 'decision', id: `d:${decision.id}`, decision });
    }
    byAnchor.delete(anchor);
  };

  pushDecisions(-1);
  for (const segment of block.segments) {
    items.push({ kind: 'segment', id: `s:${block.session.id}:${segment.sequence}`, segment });
    pushDecisions(segment.sequence);
  }
  // Decisions anchored to segments we no longer have (or never had) go at the end, in order.
  for (const list of byAnchor.values()) {
    for (const decision of list) {
      items.push({ kind: 'decision', id: `d:${decision.id}`, decision });
    }
  }

  // Stories already shown as an accepted decision are not repeated.
  for (const story of block.stories) {
    if (!decidedStoryIds.has(story.id)) {
      items.push({ kind: 'story', id: `st:${story.id}`, story });
    }
  }
  return items;
}

/** The timestamp a feed item sorts by, in epoch ms (NaN when the source carried none). */
function itemTime(item: FeedItem): number {
  switch (item.kind) {
    case 'segment':
      return Date.parse(item.segment.occurredAt);
    case 'decision':
      return Date.parse(item.decision.occurredAt);
    case 'story':
      return item.story.createdAt ? Date.parse(item.story.createdAt) : Number.NaN;
    default:
      return Number.NaN;
  }
}

/**
 * Historical merge: segments, decisions and stories are placed by absolute time.
 * The sort is stable and NaN-tolerant — items lacking a timestamp keep their
 * relative input order (segments first, then decisions, then stories).
 */
function buildChronologicalItems(
  block: BuildInput,
  decidedStoryIds: ReadonlySet<string | null>,
): FeedItem[] {
  const items: FeedItem[] = [];
  for (const segment of block.segments) {
    items.push({ kind: 'segment', id: `s:${block.session.id}:${segment.sequence}`, segment });
  }
  for (const decision of block.decisions) {
    items.push({ kind: 'decision', id: `d:${decision.id}`, decision });
  }
  for (const story of block.stories) {
    if (!decidedStoryIds.has(story.id)) {
      items.push({ kind: 'story', id: `st:${story.id}`, story });
    }
  }
  return items
    .map((item, index) => ({ item, index }))
    .sort((a, b) => {
      const ta = itemTime(a.item);
      const tb = itemTime(b.item);
      if (Number.isNaN(ta) && Number.isNaN(tb)) return a.index - b.index;
      if (Number.isNaN(ta)) return 1;
      if (Number.isNaN(tb)) return -1;
      return ta === tb ? a.index - b.index : ta - tb;
    })
    .map((entry) => entry.item);
}

// ---- Speaker display (diarization) ----

/** A speaker's stable display assignment: a 1-based number and a feed side. */
export interface SpeakerDisplay {
  /** 1-based index in first-seen order (drives the "Speaker N" label). */
  index: number;
  /** Which side of the feed this speaker's bubbles sit on. */
  side: 'left' | 'right';
}

/**
 * Assigns each distinct non-empty `speakerLabel` a stable display: numbered in
 * first-seen order, alternating side (1st→left, 2nd→right, 3rd→left, …). Returns
 * an empty map when no segment carries a usable label (diarization off), so the
 * feed keeps its single-column left layout rather than faking alternation.
 */
export function assignSpeakerSides(
  segments: readonly { speakerLabel: string | null }[],
): Map<string, SpeakerDisplay> {
  const map = new Map<string, SpeakerDisplay>();
  for (const segment of segments) {
    const label = segment.speakerLabel?.trim();
    if (!label || map.has(label)) continue;
    const index = map.size + 1;
    map.set(label, { index, side: index % 2 === 1 ? 'left' : 'right' });
  }
  return map;
}

// ---- Priority ordering (side-panel sort) ----

/** Sort weight for a story priority — higher is more urgent, unknown values sink. */
export function priorityRank(priority: string | null | undefined): number {
  switch ((priority ?? '').toUpperCase()) {
    case 'CRITICAL':
      return 4;
    case 'HIGH':
      return 3;
    case 'MEDIUM':
      return 2;
    case 'LOW':
      return 1;
    default:
      return 0;
  }
}

/**
 * Comparator ordering stories by priority (CRITICAL → HIGH → MEDIUM → LOW),
 * breaking ties by most-recent `createdAt` so the panel's default sort is stable.
 */
export function comparePriority(
  a: { priority: string; createdAt?: string | null },
  b: { priority: string; createdAt?: string | null },
): number {
  const byPriority = priorityRank(b.priority) - priorityRank(a.priority);
  if (byPriority !== 0) return byPriority;
  return compareRecent(a, b);
}

/** Comparator ordering stories by most-recent `createdAt` first; undated ones sink. */
export function compareRecent(
  a: { createdAt?: string | null },
  b: { createdAt?: string | null },
): number {
  const ta = a.createdAt ? Date.parse(a.createdAt) : Number.NaN;
  const tb = b.createdAt ? Date.parse(b.createdAt) : Number.NaN;
  if (Number.isNaN(ta) && Number.isNaN(tb)) return 0;
  if (Number.isNaN(ta)) return 1;
  if (Number.isNaN(tb)) return -1;
  return tb - ta;
}

// ---- Decide resilience ----

/**
 * True for HTTP statuses worth ONE automatic accept/dismiss retry: network
 * failures (status 0) and server errors (5xx). Everything else — notably 409
 * SUGGESTION_ALREADY_RESOLVED and other client errors — surfaces immediately.
 */
export function isTransientDecideStatus(status: number): boolean {
  return status === 0 || (status >= 500 && status <= 599);
}

// ---- Decision queue (pending suggestions) ----

/** Adds a pending suggestion to the queue unless it is already there. */
export function addToQueue(
  queue: readonly SuggestionResponse[],
  suggestion: SuggestionResponse,
): SuggestionResponse[] {
  if (queue.some((s) => s.id === suggestion.id)) return [...queue];
  return [...queue, suggestion];
}

/** Removes a suggestion (decided here or elsewhere) from the queue. */
export function removeFromQueue(
  queue: readonly SuggestionResponse[],
  suggestionId: string,
): SuggestionResponse[] {
  return queue.filter((s) => s.id !== suggestionId);
}

/** Keeps the carousel index valid after the queue changes. */
export function clampQueueIndex(index: number, length: number): number {
  if (length === 0) return 0;
  return Math.min(Math.max(index, 0), length - 1);
}

/** Fraction of the card width a horizontal drag must clear to commit a navigation. */
export const DRAG_COMMIT_FRACTION = 0.3;
/** Absolute floor (px) for the commit threshold, so a very narrow card still needs a real drag. */
export const DRAG_COMMIT_MIN_PX = 90;

/**
 * Resolves a horizontal drag on the active card into a navigation outcome:
 * dragging LEFT (negative delta) goes to the `'next'` card, RIGHT (positive)
 * to the `'prev'` one. Returns `'snap'` (spring back to center, no navigation)
 * when the drag is below the commit threshold — max of {@link DRAG_COMMIT_MIN_PX}
 * and {@link DRAG_COMMIT_FRACTION} of the card width — or when it would run past a
 * boundary (can't go prev at index 0, can't go next at the last card). Pure so the
 * gesture's decision rule is unit-testable without a DOM.
 */
export function dragOutcome(
  deltaX: number,
  width: number,
  index: number,
  length: number,
): 'next' | 'prev' | 'snap' {
  const threshold = Math.max(DRAG_COMMIT_MIN_PX, width * DRAG_COMMIT_FRACTION);
  if (Math.abs(deltaX) < threshold) return 'snap';
  if (deltaX < 0) return index < length - 1 ? 'next' : 'snap';
  return index > 0 ? 'prev' : 'snap';
}

/** Most decorative "deck" edges rendered behind the active suggestion card. */
export const MAX_STACK_LAYERS = 3;

/**
 * How many decorative stacked-card edges to render behind the active suggestion
 * card, to convey the depth of the remaining queue: one edge per pending card
 * beyond the one on top, capped at {@link MAX_STACK_LAYERS}. Zero when a single
 * suggestion (or none) remains — a lone card shows no stack behind it.
 */
export function stackLayers(queueLength: number): number {
  if (queueLength <= 1) return 0;
  return Math.min(queueLength - 1, MAX_STACK_LAYERS);
}
