import {
  DiscoverySessionResponse,
  DisplayStory,
  SessionTranscriptSegmentMessage,
  SuggestionResponse,
  SuggestionType,
} from './discovery.models';

/**
 * Pure feed-assembly logic for the discovery chat: how a session's raw parts
 * (historical transcript text, live segments, decisions, generated stories)
 * merge into one ordered list of render-ready items. Kept free of Angular so
 * the ordering rules are unit-testable.
 */

/** An immutable record of a decision taken on a suggestion, rendered inline in the feed. */
export interface DecisionEntry {
  /** The decided suggestion's id (stable across REST and realtime events). */
  id: string;
  outcome: 'ACCEPTED' | 'DISMISSED';
  type: SuggestionType;
  /** Display label: the (draft) story title, or the clarifying question text. */
  label: string | null;
  /** Story the decision created/updated, when the backend reported one. */
  storyId: string | null;
  occurredAt: string;
  /**
   * The highest live-segment sequence present when the decision happened; the
   * entry is rendered right after that segment (-1 = before any segment).
   */
  anchorSequence: number;
}

export type FeedItem =
  | { kind: 'paragraph'; id: string; text: string }
  | { kind: 'segment'; id: string; segment: SessionTranscriptSegmentMessage }
  | { kind: 'decision'; id: string; decision: DecisionEntry }
  | { kind: 'story'; id: string; story: DisplayStory };

/** One session's chunk of the feed (sessions are the chat's natural separators). */
export interface SessionBlock {
  session: DiscoverySessionResponse;
  /** Raw transcript text (historical sessions); null until fetched or when empty. */
  transcript: string | null;
  /** Live transcript segments (realtime), ascending by sequence. */
  segments: SessionTranscriptSegmentMessage[];
  /** Decisions taken on this session's suggestions, oldest first. */
  decisions: DecisionEntry[];
  /** Stories generated by this session. */
  stories: DisplayStory[];
  /** False while the block's transcript/stories are still being fetched. */
  loaded: boolean;
}

/** Splits a historical transcript blob into paragraph items (speaker-agnostic bubbles). */
export function transcriptToItems(sessionId: string, transcript: string | null): FeedItem[] {
  if (!transcript) return [];
  return transcript
    .split(/\n+/)
    .map((line) => line.trim())
    .filter((line) => line.length > 0)
    .map((text, index) => ({ kind: 'paragraph' as const, id: `${sessionId}:p${index}`, text }));
}

/** Upserts a live segment by sequence (a hypothesis is replaced by its final), keeping ascending order. */
export function upsertSegment(
  segments: readonly SessionTranscriptSegmentMessage[],
  segment: SessionTranscriptSegmentMessage,
): SessionTranscriptSegmentMessage[] {
  return [...segments.filter((s) => s.sequence !== segment.sequence), segment].sort(
    (a, b) => a.sequence - b.sequence,
  );
}

/** The highest final segment sequence, or -1 when there are none (decision anchor). */
export function lastSequence(segments: readonly SessionTranscriptSegmentMessage[]): number {
  return segments.reduce((max, s) => Math.max(max, s.sequence), -1);
}

/** Builds a decision entry from a resolved suggestion, anchored after the current last segment. */
export function toDecisionEntry(
  suggestion: SuggestionResponse,
  outcome: 'ACCEPTED' | 'DISMISSED',
  anchorSequence: number,
  occurredAt: string = new Date().toISOString(),
): DecisionEntry {
  return {
    id: suggestion.id,
    outcome,
    type: suggestion.type,
    label: suggestion.type === 'CLARIFYING_QUESTION' ? suggestion.question : suggestion.draftTitle,
    storyId: suggestion.resolvedStoryId ?? suggestion.targetStoryId,
    occurredAt,
    anchorSequence,
  };
}

/**
 * Merges one session's parts into its ordered feed items:
 * 1. historical transcript paragraphs,
 * 2. live segments with each decision inserted right after its anchor segment,
 * 3. generated stories not already represented by an accepted decision.
 */
export function buildSessionItems(block: {
  session: { id: string };
  transcript: string | null;
  segments: readonly SessionTranscriptSegmentMessage[];
  decisions: readonly DecisionEntry[];
  stories: readonly DisplayStory[];
}): FeedItem[] {
  const items: FeedItem[] = transcriptToItems(block.session.id, block.transcript);

  // Decisions grouped by anchor so several decisions after one segment keep their order.
  const byAnchor = new Map<number, DecisionEntry[]>();
  for (const decision of block.decisions) {
    const list = byAnchor.get(decision.anchorSequence) ?? [];
    list.push(decision);
    byAnchor.set(decision.anchorSequence, list);
  }
  const pushDecisions = (anchor: number): void => {
    for (const decision of byAnchor.get(anchor) ?? []) {
      items.push({ kind: 'decision', id: `d:${decision.id}`, decision });
    }
    byAnchor.delete(anchor);
  };

  pushDecisions(-1);
  for (const segment of block.segments) {
    items.push({ kind: 'segment', id: `s:${block.session.id}:${segment.sequence}`, segment });
    pushDecisions(segment.sequence);
  }
  // Decisions anchored to segments we no longer have (or never had) go at the end, in order.
  for (const list of byAnchor.values()) {
    for (const decision of list) {
      items.push({ kind: 'decision', id: `d:${decision.id}`, decision });
    }
  }

  // Stories already shown as an accepted decision are not repeated.
  const decidedStoryIds = new Set(
    block.decisions.filter((d) => d.outcome === 'ACCEPTED' && d.storyId).map((d) => d.storyId),
  );
  for (const story of block.stories) {
    if (!decidedStoryIds.has(story.id)) {
      items.push({ kind: 'story', id: `st:${story.id}`, story });
    }
  }
  return items;
}

// ---- Decision queue (pending suggestions) ----

/** Adds a pending suggestion to the queue unless it is already there. */
export function addToQueue(
  queue: readonly SuggestionResponse[],
  suggestion: SuggestionResponse,
): SuggestionResponse[] {
  if (queue.some((s) => s.id === suggestion.id)) return [...queue];
  return [...queue, suggestion];
}

/** Removes a suggestion (decided here or elsewhere) from the queue. */
export function removeFromQueue(
  queue: readonly SuggestionResponse[],
  suggestionId: string,
): SuggestionResponse[] {
  return queue.filter((s) => s.id !== suggestionId);
}

/** Keeps the carousel index valid after the queue changes. */
export function clampQueueIndex(index: number, length: number): number {
  if (length === 0) return 0;
  return Math.min(Math.max(index, 0), length - 1);
}
