name: Release

on:
  push:
    branches: ['release/**']

concurrency:
  group: delivery-${{ github.ref }}
  cancel-in-progress: false

permissions:
  contents: read

jobs:
  delivery:
    name: Deliver
    uses: ./.github/workflows/delivery.yml
    secrets: inherit
    permissions:
      contents: read
      packages: write
      pull-requests: write
