import { ChangeDetectionStrategy, Component, computed, input } from '@angular/core';
import { TranslocoPipe } from '@jsverse/transloco';
import { provideIcons } from '@ng-icons/core';
import {
  lucideChevronDown,
  lucideChevronUp,
  lucideChevronsUp,
  lucideCircleCheck,
  lucideCircleDashed,
  lucideCircleX,
  lucideEqual,
  lucideGitMerge,
  lucidePencilLine,
  lucideSparkles,
  lucideUpload,
} from '@ng-icons/lucide';
import { HlmIcon } from '../../../../shared/ui';

const CHIP =
  'inline-flex items-center gap-1 whitespace-nowrap rounded-full px-2 py-0.5 font-medium';

interface ChipStyle {
  icon: string;
  tone: string;
}

const PRIORITY: Record<string, ChipStyle> = {
  CRITICAL: {
    icon: 'lucideChevronsUp',
    tone: 'bg-priority-critical-soft text-priority-critical',
  },
  HIGH: { icon: 'lucideChevronUp', tone: 'bg-priority-high-soft text-priority-high' },
  MEDIUM: { icon: 'lucideEqual', tone: 'bg-secondary text-secondary-foreground' },
  LOW: { icon: 'lucideChevronDown', tone: 'bg-secondary text-muted-foreground' },
};

const STATUS: Record<string, ChipStyle> = {
  DRAFT: {
    icon: 'lucideCircleDashed',
    tone: 'bg-pending-soft text-pending ring-1 ring-inset ring-pending-border',
  },
  APPROVED: {
    icon: 'lucideCircleCheck',
    tone: 'bg-verified-soft text-verified ring-1 ring-inset ring-verified-border',
  },
  REJECTED: { icon: 'lucideCircleX', tone: 'bg-secondary text-muted-foreground' },
  MERGED: { icon: 'lucideGitMerge', tone: 'bg-secondary text-muted-foreground' },
  EXPORTED: { icon: 'lucideUpload', tone: 'bg-secondary text-secondary-foreground' },
};

const ICONS = provideIcons({
  lucideChevronDown,
  lucideChevronUp,
  lucideChevronsUp,
  lucideCircleCheck,
  lucideCircleDashed,
  lucideCircleX,
  lucideEqual,
  lucideGitMerge,
  lucidePencilLine,
  lucideSparkles,
  lucideUpload,
});

/**
 * Priority chip with a direction glyph (⇈ ↑ = ↓) so the level never rests on colour
 * alone: critical red, high orange, medium/low neutral — red stays reserved for the
 * truly urgent end of the scale instead of tinting half the backlog.
 */
@Component({
  selector: 'app-priority-badge',
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [HlmIcon, TranslocoPipe],
  viewProviders: [ICONS],
  template: `
    <span [class]="classes()" data-testid="priority-badge" [attr.data-priority]="key()">
      <hlm-icon [name]="style().icon" size="12px" aria-hidden="true" />
      {{ 'stories.priority.' + key() | transloco }}
    </span>
  `,
})
export class PriorityBadge {
  readonly priority = input.required<string | null | undefined>();
  readonly size = input<'sm' | 'md'>('md');

  protected readonly key = computed(() => (this.priority() ?? 'MEDIUM').toUpperCase());
  protected readonly style = computed(() => PRIORITY[this.key()] ?? PRIORITY['MEDIUM']);
  protected readonly classes = computed(
    () => `${CHIP} ${this.size() === 'sm' ? 'text-[11px]' : 'text-xs'} ${this.style().tone}`,
  );
}

/**
 * Review-status chip. Draft (awaiting review) is amber with a dashed ring; approved
 * (validated by the team) is emerald with a check — the two states the analyst must
 * tell apart at a glance. The tooltip spells out what the status means.
 */
@Component({
  selector: 'app-story-status-badge',
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [HlmIcon, TranslocoPipe],
  viewProviders: [ICONS],
  template: `
    <span
      [class]="classes()"
      [title]="'stories.statusHint.' + key() | transloco"
      data-testid="status-badge"
      [attr.data-status]="key()"
    >
      <hlm-icon [name]="style().icon" size="12px" aria-hidden="true" />
      {{ 'stories.status.' + key() | transloco }}
    </span>
  `,
})
export class StoryStatusBadge {
  readonly status = input.required<string | null | undefined>();

  protected readonly key = computed(() => {
    const status = (this.status() ?? 'DRAFT').toUpperCase();
    return STATUS[status] ? status : 'DRAFT';
  });
  protected readonly style = computed(() => STATUS[this.key()]);
  protected readonly classes = computed(() => `${CHIP} text-xs ${this.style().tone}`);
}

/**
 * Where a story came from: generated by the AI in a capture session (violet, sparkles)
 * or written by hand. Stories carry their `sessionId` only when the AI produced them.
 */
@Component({
  selector: 'app-origin-badge',
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [HlmIcon, TranslocoPipe],
  viewProviders: [ICONS],
  template: `
    @if (fromSession()) {
      <span
        class="inline-flex items-center gap-1 whitespace-nowrap rounded-full px-2 py-0.5 font-medium bg-ai-soft text-xs text-ai"
        [title]="'stories.origin.aiHint' | transloco"
        data-testid="origin-badge"
        data-origin="ai"
      >
        <hlm-icon name="lucideSparkles" size="12px" aria-hidden="true" />
        {{ 'stories.origin.ai' | transloco }}
      </span>
    } @else {
      <span
        class="inline-flex items-center gap-1 whitespace-nowrap rounded-full px-2 py-0.5 font-medium text-xs text-muted-foreground"
        [title]="'stories.origin.manualHint' | transloco"
        data-testid="origin-badge"
        data-origin="manual"
      >
        <hlm-icon name="lucidePencilLine" size="12px" aria-hidden="true" />
        {{ 'stories.origin.manual' | transloco }}
      </span>
    }
  `,
})
export class OriginBadge {
  readonly sessionId = input<string | null | undefined>(null);
  protected readonly fromSession = computed(() => !!this.sessionId());
}
